In [1]:
#!pip install kmodes

In [1]:
import numpy as np
import pandas as pd

from kmodes.kprototypes import KPrototypes

In [2]:
df = pd.read_csv('Marketing.csv')

In [3]:
df.columns

Index(['Customer', 'State', 'CLV', 'Coverage', 'Income', 'loc_type',
       'monthly_premium', 'months_last_claim', 'Months_Since_Policy_Inception',
       'Total_Claim_Amount', 'Vehicle_Class', 'avg_vehicle_age'],
      dtype='object')

In [4]:
df

Customer       State           CLV  Coverage  Income  loc_type  \
0     BU79786  Washington   2763.519279     Basic   56274  Suburban   
1     AI49188      Nevada  12887.431650   Premium   48767  Suburban   
2     HB64268  Washington   2813.692575     Basic   43836     Rural   
3     OC83172      Oregon   8256.297800     Basic   62902     Rural   
4     XZ87318      Oregon   5380.898636     Basic   55350  Suburban   
...       ...         ...           ...       ...     ...       ...   
6812  TF56202  California   5032.165498     Basic   66367  Suburban   
6813  YM19146  California   4100.398533   Premium   47761  Suburban   
6814  LA72316  California  23405.987980     Basic   71941     Urban   
6815  PK87824  California   3096.511217  Extended   21604  Suburban   
6816  UP19263  California   7524.442436  Extended   21941  Suburban   

      monthly_premium  months_last_claim  Months_Since_Policy_Inception  \
0                  69                 32                              5   
1                 108                 18                             38   
2                  73                 12                             44   
3                  69                 14                             94   
4                  67                  0                             13   
...               ...                ...                            ...   
6812               64                  6                             48   
6813              104                 16                             58   
6814               73                 18                             89   
6815               79                 14                             28   
6816               96                 34                              3   

      Total_Claim_Amount  Vehicle_Class  avg_vehicle_age  
0             384.811147   Two-Door Car        40.696695  
1             566.472247   Two-Door Car        48.755298  
2             138.130879  Four-Door Car        70.394474  
3             159.383042   Two-Door Car        53.460212  
4             321.600000  Four-Door Car        32.811507  
...                  ...            ...              ...  
6812          307.200000   Two-Door Car        37.492591  
6813          541.282007  Four-Door Car        48.946675  
6814          198.234764  Four-Door Car        65.310053  
6815          379.200000  Four-Door Car        48.002914  
6816          691.200000  Four-Door Car        45.151858  

[6817 rows x 12 columns]

In [5]:
df=df.drop(['Customer','Vehicle_Class','avg_vehicle_age','months_last_claim','Total_Claim_Amount'],axis=1)

In [6]:
df.head(3)

State           CLV Coverage  Income  loc_type  monthly_premium  \
0  Washington   2763.519279    Basic   56274  Suburban               69   
1      Nevada  12887.431650  Premium   48767  Suburban              108   
2  Washington   2813.692575    Basic   43836     Rural               73   

   Months_Since_Policy_Inception  
0                              5  
1                             38  
2                             44

In [7]:
df_array=df.values

In [12]:
df_array[:, 1] = df_array[:, 1].astype(float)
df_array[:, 3] = df_array[:, 3].astype(float)
df_array[:, 5] = df_array[:, 5].astype(float)
df_array[:, 6] = df_array[:, 6].astype(float)

In [9]:
kproto = KPrototypes(n_clusters=3, verbose=2,max_iter=20)

In [10]:
clusters = kproto.fit_predict(df_array, categorical=[0, 2, 4])

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 1, iteration: 1/20, moves: 735, ncost: 786494325195.457
Run: 1, iteration: 2/20, moves: 82, ncost: 785840712837.4766
Run: 1, iteration: 3/20, moves: 35, ncost: 785681595789.9498
Run: 1, iteration: 4/20, moves: 11, ncost: 785652773397.5133
Run: 1, iteration: 5/20, moves: 16, ncost: 785609292387.8529
Run: 1, iteration: 6/20, moves: 13, ncost: 785587014534.5712
Run: 1, iteration: 7/20, moves: 6, ncost: 785580196116.0236
Run: 1, iteration: 8/20, moves: 4, ncost: 785577307058.1285
Run: 1, iteration: 9/20, moves: 4, ncost: 785574087818.5051
Run: 1, iteration: 10/20, moves: 3, ncost: 785572843787.3956
Run: 1, iteration: 11/20, moves: 0, ncost: 785572843787.3956
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 2, iteration: 1/20, moves: 1240, ncost: 920114249587.3894
Run: 2, iteration: 2/20, moves: 792, ncost: 838309773787.205
Run: 2, iteration: 3/20, moves: 532, ncost: 8032

In [13]:
print(kproto.cluster_centroids_)

[array([[8.32854658e+03, 5.46971570e+04, 9.51439218e+01, 4.91401956e+01],
       [8.04603174e+03, 8.29419437e+04, 9.09288472e+01, 4.76558191e+01],
       [8.03462666e+03, 2.66552219e+04, 9.26149807e+01, 4.69621981e+01]]), array([['California', 'Basic', 'Suburban'],
       ['California', 'Basic', 'Rural'],
       ['California', 'Basic', 'Suburban']], dtype='<U10')]


In [20]:
#1st center
kproto.cluster_centroids_[0][0],kproto.cluster_centroids_[1][0],

(array([8.32854658e+03, 5.46971570e+04, 9.51439218e+01, 4.91401956e+01]),
 array(['California', 'Basic', 'Suburban'], dtype='<U10'))

In [23]:
#2nd center
kproto.cluster_centroids_[0][1],kproto.cluster_centroids_[1][1],

(array([8.04603174e+03, 8.29419437e+04, 9.09288472e+01, 4.76558191e+01]),
 array(['California', 'Basic', 'Rural'], dtype='<U10'))

In [24]:
#3rd center
kproto.cluster_centroids_[0][2],kproto.cluster_centroids_[1][2],

(array([ 8034.62665515, 26655.2219111 ,    92.61498075,    46.96219811]),
 array(['California', 'Basic', 'Suburban'], dtype='<U10'))

In [25]:
predictions=[]
for c in clusters:
    predictions.append(c)

In [26]:
predictions

[0,
 0,
 0,
 0,
 0,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 0,
 0,
 0,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 2,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 2,
 2,
 2,
 2,
 0,
 2,
 2,
 0,
 2,
 1,
 0,
 2,
 1,
 2,
 1,
 2,
 2,
 0,
 0,
 2,
 0,
 2,
 2,
 2,
 0,
 2,
 2,
 2,
 1,
 1,
 0,
 1,
 2,
 2,
 0,
 2,
 0,
 0,
 0,
 2,
 2,
 1,
 0,
 2,
 2,
 0,
 0,
 2,
 2,
 1,
 1,
 0,
 1,
 2,
 2,
 0,
 0,
 2,
 2,
 2,
 0,
 2,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 2,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 0,
 2,
 2,
 0,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 0,
 2,
 0,
 1,
 2,
 2,
 2,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 2,
 0,
 0,
 2,
 2,
 2,
 0,
 0,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 0,
 2,
 2,
 2,
 0,
 2,
 2,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 1,
 0,
 2,
 0,
 2,
 2,
 0,
 2,
 1,
 2,
 2,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 2,
 0,
 2,
 2,
 2,
 1,
 2,
 0,
 2,
 0,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 0,
 0,
 2,
 1,
 2,
 2,
 0,
 0,
 2,
 2,
 0,
 1,
 1,
 2,
 1,
 0,
 0,
 2,
 0,
 1,
 2,
 0,
 2,
 2,
 2,


In [27]:
df['cluster']=predictions

In [28]:
df

State           CLV  Coverage  Income  loc_type  monthly_premium  \
0     Washington   2763.519279     Basic   56274  Suburban               69   
1         Nevada  12887.431650   Premium   48767  Suburban              108   
2     Washington   2813.692575     Basic   43836     Rural               73   
3         Oregon   8256.297800     Basic   62902     Rural               69   
4         Oregon   5380.898636     Basic   55350  Suburban               67   
...          ...           ...       ...     ...       ...              ...   
6812  California   5032.165498     Basic   66367  Suburban               64   
6813  California   4100.398533   Premium   47761  Suburban              104   
6814  California  23405.987980     Basic   71941     Urban               73   
6815  California   3096.511217  Extended   21604  Suburban               79   
6816  California   7524.442436  Extended   21941  Suburban               96   

      Months_Since_Policy_Inception  cluster  
0                                 5        0  
1                                38        0  
2                                44        0  
3                                94        0  
4                                13        0  
...                             ...      ...  
6812                             48        0  
6813                             58        0  
6814                             89        1  
6815                             28        2  
6816                              3        2  

[6817 rows x 8 columns]

In [29]:
df.cluster.value_counts()

2    2857
0    2147
1    1813
Name: cluster, dtype: int64

In [30]:
df[df.cluster==0].head(10)

State           CLV  Coverage  Income  loc_type  monthly_premium  \
0   Washington   2763.519279     Basic   56274  Suburban               69   
1       Nevada  12887.431650   Premium   48767  Suburban              108   
2   Washington   2813.692575     Basic   43836     Rural               73   
3       Oregon   8256.297800     Basic   62902     Rural               69   
4       Oregon   5380.898636     Basic   55350  Suburban               67   
13      Oregon   5710.333115     Basic   51148     Urban               72   
14  California   8162.617053   Premium   66140  Suburban              101   
15      Oregon   2872.051273     Basic   57749  Suburban               74   
24      Nevada  18975.456110  Extended   65999     Urban              237   
25  Washington   5018.885233     Basic   54500  Suburban               63   

    Months_Since_Policy_Inception  cluster  
0                               5        0  
1                              38        0  
2                              44        0  
3                              94        0  
4                              13        0  
13                              1        0  
14                             21        0  
15                             21        0  
24                             14        0  
25                             17        0

In [31]:
df[df.cluster==1].head(10)

State           CLV  Coverage  Income  loc_type  monthly_premium  \
7   California   8798.797003   Premium   77026     Urban              110   
8      Arizona   8819.018934     Basic   99845  Suburban              110   
9   California   5384.431665     Basic   83689     Urban               70   
19      Oregon   5802.065978     Basic   97541  Suburban               72   
21     Arizona  12902.560140   Premium   86584  Suburban              111   
22      Oregon   3235.360468  Extended   75690  Suburban               80   
27     Arizona   5744.229745     Basic   68987     Urban               71   
34  Washington   2443.665166     Basic   92834  Suburban               61   
53      Oregon  22643.834780     Basic   93011     Rural              113   
56      Oregon   4974.801539     Basic   75644  Suburban               65   

    Months_Since_Policy_Inception  cluster  
7                              82        1  
8                              25        1  
9                              10        1  
19                              1        1  
21                             54        1  
22                             44        1  
27                             40        1  
34                             56        1  
53                             12        1  
56                             68        1

In [32]:
df[df.cluster==2].head(10)

State           CLV  Coverage  Income  loc_type  monthly_premium  \
5       Oregon  24127.504020     Basic   14072  Suburban               71   
6       Oregon   7388.178085  Extended   28812     Urban               93   
10      Oregon   7463.139377     Basic   24599     Rural               64   
11      Nevada   2566.867823     Basic   25049  Suburban               67   
12  California   3945.241604     Basic   28855  Suburban              101   
16  Washington   3041.791561  Extended   13789  Suburban               79   
17     Arizona  24127.504020     Basic   14072  Suburban               71   
18  California   2392.107890     Basic   17870  Suburban               61   
20  Washington   5346.916576  Extended   10511     Urban              139   
23     Arizona   2454.583540     Basic   23158  Suburban               63   

    Months_Since_Policy_Inception  cluster  
5                               3        2  
6                               7        2  
10                             50        2  
11                              7        2  
12                             59        2  
16                             49        2  
17                              3        2  
18                             91        2  
20                             64        2  
23                              6        2